stages:
  - build
  - publish

variables:
  GRADLE_USER_HOME: "$CI_PROJECT_DIR/.gradle"
  MAVEN_USER_SETTINGS: "$CI_PROJECT_DIR/maven-settings.xml"

cache:
  paths:
    - .gradle/caches
    - .gradle/caches/**

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle
  - export GRADLE_OPTS="-Dorg.gradle.daemon=false -Dorg.gradle.parallel=false"
  - mkdir -p ~/.m2
  - echo "$MAVEN_SETTINGS_XML" > ~/.m2/settings.xml

build:
  stage: build
  image: gradle:latest
  script:
    - gradle clean shadowJar
    - echo "Gefundene Artefakte:"
    - find . -type f -path "**/build/libs/*.jar" ! -path "**/.gradle/**" -exec ls -lh {} \;

  artifacts:
    paths:
      - "**/build/libs/*.jar"
    exclude:
      - .gradle/**
      - "**/.gradle/**"
      - "./build-logic/**"

publish:
  stage: publish
  image: gradle:latest
  script:
    - gradle publish
  dependencies:
    - build
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH