name: '${name}'
version: '${project.version}'
main: ${project.mainClass}
description: '${project.description}'
api-version: '${project.apiVersion}'
bootstrapper: ${project.bootstrapper}
loader: ${project.loader}
authors: [${project.authors}]
website: '${project.url}'

dependencies:
  server:
    CommandAPI:
      load: BEFORE
      required: true
      join-classpath: true
    CoreProtect:
      load: BEFORE
      required: false
      join-classpath: true
    NBTAPI:
      load: BEFORE
      required: true
      join-classpath: true