package dev.slne.surf.essentials

import dev.slne.surf.essentials.command.*
import dev.slne.surf.essentials.command.minecraft.*
import dev.slne.surf.essentials.command.table.*

object PaperCommandManager {
    fun registerAll() {
        advancementCommand()
        opCommand()
        deopCommand()
        flyCommand()
        healCommand()
        hatCommand()
        listCommand()
        trashCommand()
        backCommand()
        spawnCommand()
        clearCommand()
        gameModeCommand()
        gameModeOfflineCommand()
        repairCommand()
        changeSlotCommand()
        strikeCommand()
        giveCommand()
        infoCommand()
        itemEditCommand()
        teleportCommand()
        teleportOfflineCommand()
        teleportRandomCommand()
        teleportToTopCommand()
        enchantmentCommand()
        whitelistCommand()
        hurtCommand()
        summonCommand()
        fillStackCommand()
        setWorldSpawnCommand()
        setPlayerIdleTimeoutCommand()
        seedCommand()
        rideCommand()
        reloadCommand()
        godCommand()
        killCommand()
        speedCommand()
        suicideCommand()
        functionCommand()
        anvilCommand()
        cartographyTableCommand()
        grindstoneCommand()
        loomCommand()
        smithingTableCommand()
        stoneCutterCommand()
        workbenchCommand()
        difficultyCommand()
        defaultGameModeCommand()
        spawnerCommand()
        broadcastCommand()
        effectCommand()
        spectateCommand()
        weatherCommand()
        soundCommand()
        stopCommand()
        restartCommand()

        if (!plugin.isSurvivalServer()) {
            makeSpecialCommand()
            signCommand()
        }

        knightCommand()
        toolCommand()
        experienceCommand()
        gameRuleCommand()
        executeCommandAdditions()
        timeCommand()
        skinChangeCommand()
        worldCommand()
        pingCommand()
    }
}